### ISSUE TITLE
Custom CSS are overwritten by default values

### ISSUE THREAD

**Issue by a-grid-studio** [belaviyo/dark-theme-for-google#1]
Custom CSS rules are overwritten by css variables set in the option panel.
In data/inject.js, there is the clean(sheet) function that adjust all colors, backgrounds and borders of the stylesheet which is very clever. 

But in my opinion, it should not overwritten custom css values.

Maybe you could try to append custom css to the stylesheet after the call of clean(sheet) function.

**Comment by belaviyo** [comment]
What is your extension version? The custom CSS is added within a `style.dark` element, so it is not supposed to be sent to the `clean()` object.

**Comment by a-grid-studio** [comment]
I'm using Google Chrome (V 88.0.4324.182) with Dark Theme for Google™ (V 0.4.5) on MacOS.

For instance, on google.com result page, I'm trying to apply this custom CSS : 
`#result-stats {
color: #9aa0a6;
}` 

When I save this on the option panel, changes are well applied. But when I refresh the page or open a new one, CSS are overwritten like so :
`#result-stats { color: var(--front-color); }`

Which is the css variable used for the "Main font color" in the option panel, right ?
