### ISSUE TITLE
Custom Css are injected when dark mode is off

### ISSUE THREAD

**Issue by a-grid-studio** [belaviyo/dark-theme-for-google#2]
I solved this issue by prepending ".dark". to all selectors.
But in my opinion, custom css rules should not be injected when dark mode is off

**Comment by belaviyo** [comment]
What is your browser? How about the extension version?

**Comment by a-grid-studio** [comment]
It works fine now ! I don't know how, extension update ? Or maybe I've previously mess up something with the inspector.
For your info, I'm using Google Chrome (V 88.0.4324.182) with Dark Theme for Google™ (V 0.4.5) on MacOS.
